// src/utils/teamLogos.js

const teamLogos = {
    // 🏀 NBA
    "Lakers": "https://a.espncdn.com/i/teamlogos/nba/500/lal.png",
    "Warriors": "https://a.espncdn.com/i/teamlogos/nba/500/gs.png",
    "Celtics": "https://a.espncdn.com/i/teamlogos/nba/500/bos.png",
    "Bulls": "https://a.espncdn.com/i/teamlogos/nba/500/chi.png",
    "Spurs": "https://a.espncdn.com/i/teamlogos/nba/500/sa.png",
    "Heat": "https://a.espncdn.com/i/teamlogos/nba/500/mia.png",
    "Nets": "https://a.espncdn.com/i/teamlogos/nba/500/bkn.png",
    "Knicks": "https://a.espncdn.com/i/teamlogos/nba/500/ny.png",
    "76ers": "https://a.espncdn.com/i/teamlogos/nba/500/phi.png",
    "Clippers": "https://a.espncdn.com/i/teamlogos/nba/500/lac.png",
    "Raptors": "https://a.espncdn.com/i/teamlogos/nba/500/tor.png",
    "Bucks": "https://a.espncdn.com/i/teamlogos/nba/500/mil.png",
    "Suns": "https://a.espncdn.com/i/teamlogos/nba/500/phx.png",
    "Grizzlies": "https://a.espncdn.com/i/teamlogos/nba/500/mem.png",
    "Kings": "https://a.espncdn.com/i/teamlogos/nba/500/sac.png",
    "Pelicans": "https://a.espncdn.com/i/teamlogos/nba/500/no.png",
    "Mavericks": "https://a.espncdn.com/i/teamlogos/nba/500/dal.png",
    "Thunder": "https://a.espncdn.com/i/teamlogos/nba/500/okc.png",
    "Jazz": "https://a.espncdn.com/i/teamlogos/nba/500/utah.png",
    "Trail Blazers": "https://a.espncdn.com/i/teamlogos/nba/500/por.png",
    "Hawks": "https://a.espncdn.com/i/teamlogos/nba/500/atl.png",
    "Nuggets": "https://a.espncdn.com/i/teamlogos/nba/500/den.png",
    "Rockets": "https://a.espncdn.com/i/teamlogos/nba/500/hou.png",
    "Pistons": "https://a.espncdn.com/i/teamlogos/nba/500/det.png",
    "Cavaliers": "https://a.espncdn.com/i/teamlogos/nba/500/cle.png",
    "Magic": "https://a.espncdn.com/i/teamlogos/nba/500/orl.png",
    "Hornets": "https://a.espncdn.com/i/teamlogos/nba/500/cha.png",
    "Wizards": "https://a.espncdn.com/i/teamlogos/nba/500/wsh.png",
    "Pacers": "https://a.espncdn.com/i/teamlogos/nba/500/ind.png",
    "Timberwolves": "https://a.espncdn.com/i/teamlogos/nba/500/min.png",
  
    // 🏈 NFL
    "Chiefs": "https://a.espncdn.com/i/teamlogos/nfl/500/kc.png",
    "Eagles": "https://a.espncdn.com/i/teamlogos/nfl/500/phi.png",
    "Cowboys": "https://a.espncdn.com/i/teamlogos/nfl/500/dal.png",
    "49ers": "https://a.espncdn.com/i/teamlogos/nfl/500/sf.png",
    "Packers": "https://a.espncdn.com/i/teamlogos/nfl/500/gb.png",
    "Steelers": "https://a.espncdn.com/i/teamlogos/nfl/500/pit.png",
    "Patriots": "https://a.espncdn.com/i/teamlogos/nfl/500/ne.png",
    "Bills": "https://a.espncdn.com/i/teamlogos/nfl/500/buf.png",
    "Jets": "https://a.espncdn.com/i/teamlogos/nfl/500/nyj.png",
    "Giants": "https://a.espncdn.com/i/teamlogos/nfl/500/nyg.png",
    "Dolphins": "https://a.espncdn.com/i/teamlogos/nfl/500/mia.png",
    "Ravens": "https://a.espncdn.com/i/teamlogos/nfl/500/bal.png",
    "Bengals": "https://a.espncdn.com/i/teamlogos/nfl/500/cin.png",
    "Broncos": "https://a.espncdn.com/i/teamlogos/nfl/500/den.png",
    "Raiders": "https://a.espncdn.com/i/teamlogos/nfl/500/lv.png",
    "Chargers": "https://a.espncdn.com/i/teamlogos/nfl/500/lac.png",
    "Seahawks": "https://a.espncdn.com/i/teamlogos/nfl/500/sea.png",
    "Bears": "https://a.espncdn.com/i/teamlogos/nfl/500/chi.png",
    "Buccaneers": "https://a.espncdn.com/i/teamlogos/nfl/500/tb.png",
    "Lions": "https://a.espncdn.com/i/teamlogos/nfl/500/det.png",
    "Vikings": "https://a.espncdn.com/i/teamlogos/nfl/500/min.png",
    "Colts": "https://a.espncdn.com/i/teamlogos/nfl/500/ind.png",
    "Texans": "https://a.espncdn.com/i/teamlogos/nfl/500/hou.png",
    "Titans": "https://a.espncdn.com/i/teamlogos/nfl/500/ten.png",
    "Jaguars": "https://a.espncdn.com/i/teamlogos/nfl/500/jax.png",
    "Saints": "https://a.espncdn.com/i/teamlogos/nfl/500/no.png",
    "Panthers": "https://a.espncdn.com/i/teamlogos/nfl/500/car.png",
    "Commanders": "https://a.espncdn.com/i/teamlogos/nfl/500/wsh.png",
    " F Cardinals": "https://a.espncdn.com/i/teamlogos/nfl/500/ari.png",
    "Falcons": "https://a.espncdn.com/i/teamlogos/nfl/500/atl.png",
    "Rams": "https://a.espncdn.com/i/teamlogos/nfl/500/lar.png",
    "Browns": "https://a.espncdn.com/i/teamlogos/nfl/500/cle.png",
  
    // ⚾ MLB
    "Yankees": "https://a.espncdn.com/i/teamlogos/mlb/500/nyy.png",
    "Red Sox": "https://a.espncdn.com/i/teamlogos/mlb/500/bos.png",
    "Dodgers": "https://a.espncdn.com/i/teamlogos/mlb/500/lad.png",
    "Cubs": "https://a.espncdn.com/i/teamlogos/mlb/500/chc.png",
    "Giants": "https://a.espncdn.com/i/teamlogos/mlb/500/sf.png",
    "Astros": "https://a.espncdn.com/i/teamlogos/mlb/500/hou.png",
    "Braves": "https://a.espncdn.com/i/teamlogos/mlb/500/atl.png",
    "Cardinals": "https://a.espncdn.com/i/teamlogos/mlb/500/stl.png",
    "Phillies": "https://a.espncdn.com/i/teamlogos/mlb/500/phi.png",
    "Mets": "https://a.espncdn.com/i/teamlogos/mlb/500/nym.png",
    "Brewers": "https://a.espncdn.com/i/teamlogos/mlb/500/mil.png",
    "Padres": "https://a.espncdn.com/i/teamlogos/mlb/500/sd.png",
    "Rangers": "https://a.espncdn.com/i/teamlogos/mlb/500/tex.png",
    "Blue Jays": "https://a.espncdn.com/i/teamlogos/mlb/500/tor.png",
    "Rays": "https://a.espncdn.com/i/teamlogos/mlb/500/tb.png",
    "Mariners": "https://a.espncdn.com/i/teamlogos/mlb/500/sea.png",
    "Twins": "https://a.espncdn.com/i/teamlogos/mlb/500/min.png",
    "White Sox": "https://a.espncdn.com/i/teamlogos/mlb/500/chw.png",
    "Athletics": "https://a.espncdn.com/i/teamlogos/mlb/500/oak.png",
    "Diamondbacks": "https://a.espncdn.com/i/teamlogos/mlb/500/ari.png",
    "Pirates": "https://a.espncdn.com/i/teamlogos/mlb/500/pit.png",
    "Royals": "https://a.espncdn.com/i/teamlogos/mlb/500/kc.png",
    "Orioles": "https://a.espncdn.com/i/teamlogos/mlb/500/bal.png",
    "Tigers": "https://a.espncdn.com/i/teamlogos/mlb/500/det.png",
    "Nationals": "https://a.espncdn.com/i/teamlogos/mlb/500/wsh.png",
    "Marlins": "https://a.espncdn.com/i/teamlogos/mlb/500/mia.png",
    "Rockies": "https://a.espncdn.com/i/teamlogos/mlb/500/col.png",
    "Reds": "https://a.espncdn.com/i/teamlogos/mlb/500/cin.png",
    "Guardians": "https://a.espncdn.com/i/teamlogos/mlb/500/cle.png",
    "Angels": "https://a.espncdn.com/i/teamlogos/mlb/500/laa.png"
  };
  
  export default teamLogos;
  